<a href="https://colab.research.google.com/github/angelgomes06-ops/Semana3_exerc-cios/blob/main/df_logs_semana3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
# queremos ler a base de dados e interpretar seus campos
# (pandas, display(), info(), describe())

import pandas as pd
df_logs = pd.read_csv('/content/logs_seguranca_aula.csv')

display(df_logs.head(10))


# SEMPRE QUE TEMOS UM "timestamp" DEVEMOS VERIFICAR SE ELE É UM
df_logs['timestamp'] = pd.to_datetime(df_logs['timestamp'])
df_logs.info()
df_logs.describe()
# conversao feita para trabalhar com data/hora (campo veio como texto e transformou data/hora)

,timestamp,user,ip_address,action,status,resource,failed_attempts_count
0,2026-08-01 08:58:00,joao,200.100.10.5,LOGIN,SUCCESS,dashboard,0
1,2026-08-01 17:02:00,joao,200.100.10.5,LOGOUT,SUCCESS,dashboard,0
2,2026-08-01 17:05:00,maria,200.100.10.12,LOGIN,SUCCESS,financeiro,0
3,2026-08-02 00:00:15,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,1
4,2026-08-02 00:01:10,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,2
5,2026-08-02 00:03:45,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,244
6,2026-08-02 00:04:50,joao,189.45.12.99,LOGIN,SUCCESS,system,245
7,2026-08-02 00:05:12,joao,189.45.12.99,ACCESS_FILE,FAILED,folha_pagamento.csv,0
8,2026-08-02 00:06:01,joao,189.45.12.99,ACCESS_FILE,SUCCESS,helpdesk_tickets,0
9,2026-08-02 00:07:30,joao,189.45.12.99,UPLOAD_FILE,SUCCESS,Helpdesk-NEW-VERSION.exe,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   timestamp              10 non-null     datetime64[ns]
 1   user                   10 non-null     object
 2   ip_address             10 non-null     object
 3   action                 10 non-null     object
 4   status                 10 non-null     object
 5   resource               10 non-null     object
 6   failed_attempts_count  10 non-null     int64
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 692.0+ bytes

                           timestamp  failed_attempts_count
count                             10              10.000000
mean   2026-08-01 21:09:22.299999744              49.200000
min              2026-08-01 08:58:00               0.000000
25%    2026-08-01 18:48:48.750000128               0.000000
50%       2026-08-02 00:02:27.500000               0.000000
75%       2026-08-02 00:05:06.500000               1.750000
max              2026-08-02 00:07:30             245.000000
std                              NaN             102.934499

In [37]:
# descobrir logins realizados fora do horario comercial
# seg - sex - 08 - 17
# o python pode identificar dentro de um timestamp valores ramificados
df_logs['hora'] = df_logs ['timestamp'].dt.hour
df_logs['minutos'] = df_logs['timestamp'].dt.minute
display(df_logs)
df_logs['dia_da_semana'] = df_logs ['timestamp'].dt.dayofweek

# criar os filtros
#fora do horario comercial hora 0 a 7 - 17 até 23
display(df_logs[df_logs['hora'] !=  8])

# vamos exibir os dados que nao sao resource financeiro ou system

# or -----> dentro de if, for ou while
# | ----> operador OR
# and ---> dentro de if, for ou while
# & ---> operador de E ou AND

display(df_logs[(df_logs['resource'] != 'financeiro')  &
                (df_logs['resource'] != 'system')])

# or - | é quando pelo menos uma das solucoes é verdade
# and - & quando todas as solucoes sao verdade

#filtrar colunas diferentes
# somente falhas na sexta- feira

display(df_logs[(df_logs['status'] == 'FAILED') &
                (df_logs['dia_da_semana'] == 6)])

#encontrar informacoes que iniciam ou finalizam com
# starswith - inicia com
# endswith - finaliza com
# mostrar tudo que termina com .csv
display (df_logs[df_logs['resource'].str.endswith('.csv', na=False)])

,timestamp,user,ip_address,action,status,resource,failed_attempts_count,hora,minutos,dia_da_semana
0,2026-08-01 08:58:00,joao,200.100.10.5,LOGIN,SUCCESS,dashboard,0,8,58,5
1,2026-08-01 17:02:00,joao,200.100.10.5,LOGOUT,SUCCESS,dashboard,0,17,2,5
2,2026-08-01 17:05:00,maria,200.100.10.12,LOGIN,SUCCESS,financeiro,0,17,5,5
3,2026-08-02 00:00:15,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,1,0,0,6
4,2026-08-02 00:01:10,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,2,0,1,6
5,2026-08-02 00:03:45,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,244,0,3,6
6,2026-08-02 00:04:50,joao,189.45.12.99,LOGIN,SUCCESS,system,245,0,4,6
7,2026-08-02 00:05:12,joao,189.45.12.99,ACCESS_FILE,FAILED,folha_pagamento.csv,0,0,5,6
8,2026-08-02 00:06:01,joao,189.45.12.99,ACCESS_FILE,SUCCESS,helpdesk_tickets,0,0,6,6
9,2026-08-02 00:07:30,joao,189.45.12.99,UPLOAD_FILE,SUCCESS,Helpdesk-NEW-VERSION.exe,0,0,7,6

,timestamp,user,ip_address,action,status,resource,failed_attempts_count,hora,minutos,dia_da_semana
1,2026-08-01 17:02:00,joao,200.100.10.5,LOGOUT,SUCCESS,dashboard,0,17,2,5
2,2026-08-01 17:05:00,maria,200.100.10.12,LOGIN,SUCCESS,financeiro,0,17,5,5
3,2026-08-02 00:00:15,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,1,0,0,6
4,2026-08-02 00:01:10,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,2,0,1,6
5,2026-08-02 00:03:45,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,244,0,3,6
6,2026-08-02 00:04:50,joao,189.45.12.99,LOGIN,SUCCESS,system,245,0,4,6
7,2026-08-02 00:05:12,joao,189.45.12.99,ACCESS_FILE,FAILED,folha_pagamento.csv,0,0,5,6
8,2026-08-02 00:06:01,joao,189.45.12.99,ACCESS_FILE,SUCCESS,helpdesk_tickets,0,0,6,6
9,2026-08-02 00:07:30,joao,189.45.12.99,UPLOAD_FILE,SUCCESS,Helpdesk-NEW-VERSION.exe,0,0,7,6

,timestamp,user,ip_address,action,status,resource,failed_attempts_count,hora,minutos,dia_da_semana
0,2026-08-01 08:58:00,joao,200.100.10.5,LOGIN,SUCCESS,dashboard,0,8,58,5
1,2026-08-01 17:02:00,joao,200.100.10.5,LOGOUT,SUCCESS,dashboard,0,17,2,5
7,2026-08-02 00:05:12,joao,189.45.12.99,ACCESS_FILE,FAILED,folha_pagamento.csv,0,0,5,6
8,2026-08-02 00:06:01,joao,189.45.12.99,ACCESS_FILE,SUCCESS,helpdesk_tickets,0,0,6,6
9,2026-08-02 00:07:30,joao,189.45.12.99,UPLOAD_FILE,SUCCESS,Helpdesk-NEW-VERSION.exe,0,0,7,6

,timestamp,user,ip_address,action,status,resource,failed_attempts_count,hora,minutos,dia_da_semana
3,2026-08-02 00:00:15,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,1,0,0,6
4,2026-08-02 00:01:10,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,2,0,1,6
5,2026-08-02 00:03:45,joao,189.45.12.99,LOGIN_ATTEMPT,FAILED,system,244,0,3,6
7,2026-08-02 00:05:12,joao,189.45.12.99,ACCESS_FILE,FAILED,folha_pagamento.csv,0,0,5,6

,timestamp,user,ip_address,action,status,resource,failed_attempts_count,hora,minutos,dia_da_semana
7,2026-08-02 00:05:12,joao,189.45.12.99,ACCESS_FILE,FAILED,folha_pagamento.csv,0,0,5,6